### ISSUE TITLE
Running in webpack watch mode doesn't work after a recompile.

### ISSUE THREAD

**Issue by wesselvdv** [vercel/webpack-asset-relocator-loader#141]
Running in webpack watch mode doesn't work after a recompile, this results in the `__webpack_require__.ab` being scrubbed from the `output.js`

**Comment by wesselvdv** [comment]
This is my bad. RTFM.

**Comment by MynockSpit** [comment]
@wesselvdv -- Which memo? I can't see anything referring to watch mode. Maybe I'm just blind!

**Comment by wesselvdv** [comment]
@MynockSpit It's not referring to a watch mode, but to the cache mechanism introduced in webpack 5. You have to put the following in the plugins array in your config:

```typescript
    plugins: [
      {
        apply(compiler: any) {
          compiler.hooks.compilation.tap(
            'webpack-asset-relocator-loader',
            (compilation: any) => {
              relocateLoader.initAssetCache(compilation, '');
            },
          );
        },
      },
    ]
```

**Comment by MynockSpit** [comment]
Awesome, thank you!
