### ISSUE TITLE
Nextjs native module different behavior in prod mode

### ISSUE THREAD

**Issue by amarjanica** [vercel/webpack-asset-relocator-loader#178]
Native module can't be found in prod mode.
Reproduce by cloning https://github.com/amarjanica/demo-nextjs-native-module

What works:
1. start with `npm run dev` 
2. go to `http://localhost:3000/hello`

What doesn't work:
1. `npm run build && npm run start`
2. go to `http://localhost:3000/hello`

I get  a MODULE_NOT_FOUND. it is expected in `/.next/server/native-assets/index.node`, although it's actually found in `/.next/server/chunks/native-assets/index.node`.
Locally I solved this by cloning your project and modifying this block [`asset-relocator.js`](https://github.com/vercel/webpack-asset-relocator-loader/blob/d22269d06fcb55afde028789370912351fef906d/src/asset-relocator.js#L337). Depending on the NODE_ENV, I append `chunks` to the relBase.

Is this a bug?

**Comment by styfle** [comment]
It might be a bug. 

However, Next.js has its own asset relocation, so its probably best to use that instead.

```js
module.exports = {
  output: 'standalone',
}
```

https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files

**Comment by amarjanica** [comment]
Thanks for the suggestion, I tried that with node-loader too. 
Thing is webpack-asset-relocator-loader works great for `.node` on nextjs. 
It's just that one problem with production mode.

**Comment by styfle** [comment]
Are there cases where output standalone doesn’t include the .node files?

**Comment by amarjanica** [comment]
If I setup to `standalone`, the module is included in production and 
e.g. located in `./.next/standalone/.next/server/chunks/[hash].node`,
but api route requests it from `/.next/server/pages/api/[hash].node`.

Should it be in `./.next/standalone/node_modules`? Because it's not included there.

I have to use either `node-loader` or `webpack-asset-relocator-loader` for .node, otherwise
I get a **Module parse failed: Unexpected character**. The native module is compiled using neon bindings.

I've tried multiple combinations to get this to work,
the only one that works for me is the mentioned workaround at the beginning of the issue.

I'm beginning to think this issue is out of scope for this repo,
should I rather report to https://github.com/vercel/next.js?
Thanks for your help!

**Comment by styfle** [comment]
Yes please create an issue in the Next.js repo with the steps to reproduce. 

This repo is mostly stagnant now that Next.js has its own asset handling.

**Comment by amarjanica** [comment]
I'm closing this issue. It's not a bug with Next.js or a webpack-asset-relocator-loader. I managed to solve it using my own custom loader. Problem was in how __webpack_require__ path was set, and loader needed to return a raw binary data instead of text.
Thanks again for your help!
